### ISSUE TITLE
Remove redundant attribute on Athena

### ISSUE THREAD

**Issue by tehalexf** [DavisCSClub/Main-Website#150]
Re-do the changes of commit 56e52ed

**Comment by tktong** [comment]
I don't understand how this is breaking on production. The commits to both this repository and resources repository were all on integration branch.

**Comment by tehalexf** [comment]
It's working on production, not working on integration/preview.

**Comment by tktong** [comment]
Did you update your resources repository?

**Comment by tehalexf** [comment]
Yep. The screenshot above was from the preview server.

**Comment by tehalexf** [comment]
Well, I kept the changes and found a fix. I'll push that with the rest tonight.
