### ISSUE TITLE
Re-sizing certain non-repeated hours in the Tutoring Calendar deletes entry instead

### ISSUE THREAD

**Issue by tehalexf** [DavisCSClub/Main-Website#151]
Currently happening in Production, Integration, and Preview.

Reproduction:
1. Go to https://daviscsclub.org/admin/tutoring/calendar
2. Create non-repeating office hour from 5-6 on Sunday, 4/17.
3. Resize office hour to 5-6:30, select "Change Future Related Office Hours"
4. Click "Resize Office Hour" and watch as the entry disappears. 

This can be done with specific, non-repeating hours. For instance, it will not work if I create it at the same time on  a different day, say Monday. But the bug can be produced on Sunday 4/17. I have yet to figure out what dates and times cause this.

There are no errors in the console, or the server. The re-size works as expected on repeated entries.

**Comment by tktong** [comment]
Is this still happening or can we close this out?

**Comment by tehalexf** [comment]
Probably safe to close it. Haven't seen it happen for a while.
