### ISSUE TITLE
Generalization of the Build

### ISSUE THREAD

**Issue by tktong** [DavisCSClub/Main-Website#59]
Currently the system is very specific for Davis Computer Science Club. The next goal is to generalize the system as much as possible so that any club is capable of reusing our code for their own purposes.

**Comment by aaparella** [comment]
Isn't that basically asking us to make this into a framework?

**Comment by tktong** [comment]
Sort of. Maybe make it so we can create new pages and sub-websites quickly for a given organization and sub-organizations. In our case, we have our club and then we have the committees which (in my opinion) are smaller organizations.
