### ISSUE TITLE
HTTP Status 500 on Carousel Banner Deletion

### ISSUE THREAD

**Issue by tktong** [DavisCSClub/Main-Website#62]
In the process of deleting a carousel banner, the redirect is sent to a HTTP 500 page. The banner is deleted as intended, but is throwing an exception.

![capture](https://cloud.githubusercontent.com/assets/3664144/10094958/9c0e6c02-631a-11e5-9ecb-264f0be29711.PNG)

**Comment by tktong** [comment]
Not reproducible.

**Comment by aaparella** [comment]
From the log just seems like the Carousel is being referenced after it's been deleted? Not sure what you mean by deleted in this context, was this during website modification?

**Comment by tktong** [comment]
The log says that it attempted to cast a NullPointerException to a EntityIdNotFoundException. Interestingly, it seems that whatever id we pulled and showed in the tables - it didn't exists when we deleted from the database.

``` java
public void delete(long id) throws EntityIdNotFoundException {
        CarouselBanner carouselBanner = carouselBannerRepository.findCarouselBannerById(id)
                .orElseThrow(() -> new EntityIdNotFoundException(id, String.format("Carousel banner #%d could not be found.", id)));

        File file = new File(carouselBanner.getPath());
        file.delete();

        carouselBannerRepository.delete(carouselBanner);
}
```

**Comment by aaparella** [comment]
Not sure I understand when delete is called. Can you clarify a bit what it's function is?

**Comment by tktong** [comment]
Delete is called whenever we click on Delete banner in the webpage? 

It first looks for the banner in the database and throws an exception if it can't find it. Then it creates a reference to the file and deletes it on disk. Lastly, it then deletes the banner from the database.
